name: ğŸ¤– Test & Deploy AO Compute Unit

on:
  pull_request:
    branches:
      - main
    paths:
      - "servers/cu/**"
  push:
    branches:
      - main
    paths:
      - "servers/cu/**"

defaults:
  run:
    shell: bash

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: servers/cu

      - name: âš¡ Run Tests
        working-directory: servers/cu
        run: |
          npm test
        env:
          CI: true

  # Enable once we want to start versioning the CU (maybe we wont ever need to)
  # release:
  #   # Only release on main branch. Redundancy, since bump only happens on main, but just in case.
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   concurrency:
  #     group: release
  #   steps:
  #     - name: â¬‡ï¸ Checkout repo
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #         ref: main

  #     - name: â” Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         registry-url: "https://registry.npmjs.org"

  #     - name: ğŸ‘€ Env
  #       run: |
  #         echo "Event name: ${{ github.event_name }}"
  #         echo "Git ref:    ${{ github.ref }}"
  #         echo "GH actor:   ${{ github.actor }}"
  #         echo "SHA:        ${{ github.sha }}"
  #         VER=`node --version`; echo "Node ver:   $VER"
  #         VER=`npm --version`; echo "npm ver:    $VER"

  #     - name: ğŸ¤“ Set Git User
  #       run: |
  #         git config --global user.name "${{ github.actor }}"
  #         git config --global user.email "${{ github.actor }}@users.noreply.github.com"

  #     - name: âœŠ Bump
  #       id: bump
  #       uses: hyper63/hyper-ci-bump@v2.0.3
  #       with:
  #         bumpTo: 'semver'
  #         package: servers/cu

  #     - name: â¬†ï¸ Push
  #       run: |
  #         git push
  #         git push --tags

  deploy:
    runs-on: ubuntu-latest
    # Only deploy on main branch
    if: github.ref == 'refs/heads/main'
    # Uncomment if we ever start running the release job
    # needs: [test, release]
    needs: [test]
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.bump.outputs.TAG }}

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: servers/cu

      - name: ğŸ‘€ Env
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Git ref:    ${{ github.ref }}"
          echo "GH actor:   ${{ github.actor }}"
          echo "SHA:        ${{ github.sha }}"
          VER=`node --version`; echo "Node ver:   $VER"
          VER=`npm --version`; echo "npm ver:    $VER"

      - name: ğŸš€ Deploy
        working-directory: servers/cu
        env:
          DEPLOY_HOOK: ${{ secrets.CU_RENDER_DEPLOY_HOOK }}
        run: |
          node deploy.js
