name: üëß Test & Deploy AO Sequencer Unit
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "servers/su/**"
  push:
    branches:
      - main
    paths:
      - "servers/su/**"

defaults:
  run:
    shell: bash

jobs:

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: ‚¨áÔ∏è Checkout repo
  #       uses: actions/checkout@v4

  #     - name: ‚éî Setup Rust
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: 1.75.0

  #     - name: Run Tests
  #       working-directory: servers/su
  #       run: cargo test

  
  publish:
    runs-on: ubuntu-latest
    # Only publish on main branch
    if: github.ref == 'refs/heads/main'
    needs: [test]
    permissions:
      id-token: write
      contents: read
      checks: write
      packages: write
    steps:
      - name: ‚¨áÔ∏è Checkout repo
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          context: servers/su
          tags: |
            ghcr.io/permaweb/ao-su:latest
            ghcr.io/permaweb/ao-su:${{ github.sha }}
